FROM apache/airflow:2.8.2-python3.11

USER root
RUN apt-get update && \
    apt-get install -y default-jdk wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr
ENV PATH=$JAVA_HOME/bin:$PATH

USER airflow
ENV PATH="/home/airflow/.local/bin:$PATH"

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir \
        apache-airflow==2.8.2 \
        apache-airflow-providers-apache-spark \
        apache-airflow-providers-airbyte \
        apache-airflow-providers-cncf-kubernetes \
        pyspark==3.5.1
